#!/usr/bin/env python3
"""Figures for 'Certified frontiers for tensor-network contraction ordering'.

Martinis rulebook: line weight >= 2, saturated colors + distinct line styles
(greyscale-safe), data as points / references as lines, no arbitrary units
(all axes are log2 flops or dimensionless counts), parameter boxes in-plot.
F1 (sc_target sweep) is generated by this script once sweep data exists.
"""

import csv
import json
import pathlib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = pathlib.Path("/Users/liujinguo/rcode/omeco")
ART = ROOT / "articles/2026-07-23-certified-contraction-frontiers"
FIG = ART / "figures"

plt.rcParams.update({
    "font.size": 11, "axes.labelsize": 11, "xtick.labelsize": 10,
    "ytick.labelsize": 10, "legend.fontsize": 9, "lines.linewidth": 2.0,
    "axes.linewidth": 1.0, "figure.dpi": 150, "savefig.bbox": "tight",
})
BLACK, BLUE, RED, ORANGE, VIOLET = "#000000", "#0033cc", "#cc0000", "#cc6600", "#660099"


def save(fig, name):
    fig.savefig(FIG / f"{name}.pdf")
    fig.savefig(FIG / f"{name}.png")
    plt.close(fig)
    print("wrote", name)


# ---------------------------------------------------------------- F2 frontier
def fig2():
    frontier = {"reg3_250": 39.95, "sycamore_m20": 61.544}
    default = {"reg3_250": 44.285, "sycamore_m20": 71.171}
    groups = [
        ("TreeSA default sc_target=20", {"reg3_250": 44.285, "sycamore_m20": 71.171}, BLACK, "x"),
        ("cotengra hyper", {"reg3_250": 41.678, "sycamore_m20": 63.971}, RED, "s"),
        ("cotengra SA", {"reg3_250": 40.002, "sycamore_m20": 61.679}, RED, "D"),
        ("TreeSA sc_target=∞ (frontier ref)", {"reg3_250": 39.950, "sycamore_m20": 61.544}, BLUE, "o"),
    ]
    attempts = {
        "reg3_250": [40.159, 40.286, 43.454, 45.037, 39.949, 45.118, 39.950,
                     40.024, 39.996, 40.110, 40.024, 39.949, 40.114],
        "sycamore_m20": [61.726, 62.049, 72.002, 66.056, 61.800, 67.084, 61.568,
                         61.505, 61.619, 61.635, 61.571, 61.607, 61.598],
    }
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4))
    for ax, inst in zip(axes, ["reg3_250", "sycamore_m20"]):
        deltas = [a - frontier[inst] for a in attempts[inst]]
        ax.scatter(deltas, [1.0] * len(deltas), marker="v", s=45, facecolors="none",
                   edgecolors=VIOLET, linewidths=1.8,
                   label="13 search mechanisms (this work)" if inst == "reg3_250" else None)
        for label, vals, c, m in groups:
            ax.scatter([vals[inst] - frontier[inst]], [1.0], marker=m, s=70,
                       color=c, zorder=5, label=label if inst == "reg3_250" else None)
        ax.axvline(0.0, color=BLUE, ls="--", lw=2)
        ax.set_xlabel(r"tc $-$ tc$_{\mathrm{frontier}}$  [log$_2$ flops]")
        ax.set_yticks([])
        ax.set_title(inst, fontsize=11)
        ax.set_xlim(-0.6, max(12, default[inst] - frontier[inst] + 1))
    axes[0].legend(loc="upper right", frameon=False)
    save(fig, "fig2_frontier_convergence")


# ---------------------------------------------------------------- F3 bounds
def fig3():
    # (label, reg3 value, syc value, certified?)
    rows = [
        ("spectral balanced cut", 11.36, 5.76, True),
        ("line-graph tw (minor cert.)", 18.0, 22.0, True),
        ("Thm 1 sum-form (spectral)", 13.14, 9.84, True),
        ("Thm 1 sum-form (empirical)", 30.81, 47.17, False),
        ("Thm 2 dyadic-window (emp.)", 27.0, 40.0, False),
        ("Thm 2 path-DP (emp.)", 30.32, 47.01, False),
        ("balanced/carving cut", 30.0, 53.0, False),
    ]
    caps = {"reg3_250": 30.0, "sycamore_m20": 47.0}  # bisection-width cap on profile bounds
    frontier = {"reg3_250": 39.95, "sycamore_m20": 61.544}
    fig, axes = plt.subplots(1, 2, figsize=(9.5, 3.8), sharey=False)
    for ax, inst, col in zip(axes, ["reg3_250", "sycamore_m20"], [1, 2]):
        ys = range(len(rows))
        for y, r in zip(ys, rows):
            v = r[col]
            cert = r[3]
            ax.plot([0, v], [y, y], lw=2, color=BLUE if cert else ORANGE,
                    ls="-" if cert else "--")
            ax.plot([v], [y], marker="o" if cert else "s", ms=7,
                    color=BLUE if cert else ORANGE)
        ax.axvline(frontier[inst], color=BLACK, lw=2.5)
        ax.text(frontier[inst], len(rows) - 0.4, " frontier", rotation=90,
                va="top", fontsize=9)
        ax.axvline(caps[inst], color=RED, lw=2, ls=":")
        ax.text(caps[inst], -0.45, " profile-bound cap\n (bisection width)",
                fontsize=8, color=RED)
        ax.set_yticks(list(ys))
        ax.set_yticklabels([r[0] for r in rows] if inst == "reg3_250" else [])
        ax.set_xlabel(r"lower bound on tc  [log$_2$ flops]")
        ax.set_title(inst, fontsize=11)
        ax.set_xlim(0, frontier[inst] + 4)
    fig.text(0.5, 0.995, "solid/circle = certified,  dashed/square = high-confidence empirical",
             ha="center", fontsize=9)
    save(fig, "fig3_bounds_ladder")


# ---------------------------------------------------------------- F4 profile
def fig4():
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4))
    meta = {"reg3_250": (250, 30.0, None), "sycamore_m20": (561, 47.0, (141, 40))}
    for ax, inst in zip(axes, ["reg3_250", "sycamore_m20"]):
        ks, spec, emp = [], [], []
        with open(ROOT / f".worktrees/attempt-031/data/{inst}_profile.csv") as f:
            for row in csv.DictReader(f):
                k = int(row["k"])
                if k < 1:
                    continue
                ks.append(k)
                spec.append(float(row["b_spec"]))
                emp.append(float(row["b_emp_windowmin"]))
        n, bis, cert = meta[inst]
        ax.plot(ks, emp, color=BLUE, lw=2, label="empirical profile $b(k)$ (upper est.)")
        ax.plot(ks, spec, color=RED, lw=2, ls="--", label=r"spectral bound $\lambda_2 k(n{-}k)/n$")
        ax.axhline(bis, color=BLACK, lw=2, ls=":")
        ax.text(0.02 * n, bis + 0.8, "bisection width", fontsize=8)
        if cert:
            ax.plot([cert[0]], [cert[1]], marker="*", ms=14, color=ORANGE, zorder=6,
                    label="certified cut: $|S|{=}141$, $|\\partial S|{=}40$")
        ax.set_xlabel("subset size $k$  [tensors]")
        ax.set_ylabel(r"boundary $|\partial S|$  [log$_2$ size]" if inst == "reg3_250" else "")
        ax.set_title(inst, fontsize=11)
        ax.legend(loc="upper right" if inst == "reg3_250" else "lower center",
                  frameon=False, fontsize=8)
    save(fig, "fig4_isoperimetric_profiles")


# ---------------------------------------------------------------- F5 profile conservation
def fig5():
    data = {
        "reg3_250": [("TreeSA-$\\infty$", 40.024, 37, 7, 17),
                     ("plain-tc SA", 39.882, 36, 19, 26),
                     ("profile-aware SA", 39.883, 36, 18, 25)],
        "sycamore_m20": [("TreeSA-$\\infty$", 63.576, 61, 5, 6),
                         ("plain-tc SA", 61.703, 58, 4, 20),
                         ("profile-aware SA", 61.508, 57, 17, 65)],
    }
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.2))
    for ax, inst in zip(axes, data):
        rows = data[inst]
        x = range(len(rows))
        w = 0.38
        ax.bar([i - w / 2 for i in x], [r[3] for r in rows], w, color=BLUE,
               label="nodes within 1.0 of max")
        ax.bar([i + w / 2 for i in x], [r[4] for r in rows], w, color=ORANGE,
               hatch="//", label="nodes within 2.0 of max")
        for i, r in enumerate(rows):
            ax.text(i, max(r[3], r[4]) + 0.6, f"peak {r[2]}\ntc {r[1]:.2f}",
                    ha="center", fontsize=8)
        ax.set_xticks(list(x))
        ax.set_xticklabels([r[0] for r in rows], fontsize=9)
        ax.set_ylabel("count of contractions" if inst == "reg3_250" else "")
        ax.set_title(inst, fontsize=11)
        ax.set_ylim(0, max(r[4] for r in rows) * 1.35)
    axes[0].legend(frameon=False, fontsize=8)
    save(fig, "fig5_profile_conservation")


# ---------------------------------------------------------------- F6 scale
def fig6():
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4))
    # (a) budget scaling, small instances
    ax = axes[0]
    budgets = [90, 300, 900]
    ax.plot(budgets, [39.944, 39.884, 39.952], marker="o", color=BLUE,
            label="reg3_250")
    ax.plot(budgets, [61.609, 61.581, 61.505], marker="s", color=RED, ls="--",
            label="sycamore_m20")
    ax.set_xscale("log")
    ax.set_xticks(budgets)
    ax.set_xticklabels([str(b) for b in budgets])
    ax.set_xlabel("optimizer budget  [s]")
    ax.set_ylabel(r"best tc  [log$_2$ flops]")
    ax.set_title("(a) converged regime: budget-independent", fontsize=10)
    ax.legend(frameon=False)
    ax.set_ylim(35, 65)
    # (b) anytime at scale (reg3_1000)
    ax = axes[1]
    t = [5, 10, 20, 40, 90]
    ax.plot(t, [146, 137, 137, 137, 135.41], marker="o", color=BLUE,
            label="TreeSA-$\\infty$ (restart schedule)")
    ax.plot(t, [264, 264, 264, 180, 133.57], marker="s", color=RED, ls="--",
            label="single continuous anneal")
    ax.set_xlabel("wall-clock  [s]")
    ax.set_ylabel(r"best tc  [log$_2$ flops]")
    ax.set_title("(b) non-converged regime: reg3_1000", fontsize=10)
    ax.legend(frameon=False, fontsize=8)
    save(fig, "fig6_scale_regimes")


# ---------------------------------------------------------------- F7 timeline
def fig7():
    # (cycle, reg3 record, sycamore record, annotation)
    events = [
        (1, 47.02, 73.61, "v1 gate: speed bar met\nby schedule hygiene"),
        (2, 39.95, 61.51, "8 mechanisms 'beat'\nreferences 20-800x"),
        (2.5, 39.90, 61.53, "tuned reference\nreclaims records"),
        (3, 39.95, 61.54, "cotengra rows;\npure-tc objective"),
        (4, 39.95, 61.54, "certified bounds;\nhierarchical nulls"),
        (5, 39.95, 61.54, "profile program;\nscorer bias fixed"),
        (6, 39.95, 61.54, "Thm 2: profile bounds\ncapped (impossibility)"),
    ]
    fig, ax = plt.subplots(figsize=(9, 3.4))
    xs = [e[0] for e in events]
    ax.step(xs, [e[1] for e in events], where="post", color=BLUE, lw=2.5,
            label="reg3_250 best tc")
    ax.step(xs, [e[2] for e in events], where="post", color=RED, lw=2.5, ls="--",
            label="sycamore_m20 best tc")
    ax.axhline(53, color=RED, lw=1.5, ls=":")
    ax.text(5.6, 53.6, "certified LB (sycamore)", fontsize=8, color=RED)
    for x, _, y, note in events:
        ax.annotate(note, (x, y), textcoords="offset points", xytext=(2, 14),
                    fontsize=6.5)
    ax.set_xlabel("research-loop cycle")
    ax.set_ylabel(r"best verified tc  [log$_2$ flops]")
    ax.set_ylim(35, 80)
    ax.legend(frameon=False, loc="center right")
    save(fig, "fig7_methodology_timeline")


# ---------------------------------------------------------------- F1 sweep (if data ready)
def fig1():
    path = ART / "data/sweep_sctarget.jsonl"
    if not path.exists() or path.stat().st_size == 0:
        print("F1: sweep data not ready, skipping")
        return
    import collections
    runs = collections.defaultdict(list)
    for line in open(path):
        d = json.loads(line)
        runs[(d["instance"], d["sc_target"])].append(d["result"]["tc"])
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.4))
    order = {"reg3_250": ["10", "15", "20", "25", "30", "34", "40", "50", "inf"],
             "sycamore_m20": ["20", "30", "40", "45", "50", "53", "60", "70", "inf"]}
    frontier = {"reg3_250": 39.95, "sycamore_m20": 61.544}
    natural = {"reg3_250": 34, "sycamore_m20": 53}
    for ax, inst in zip(axes, order):
        xs, meds, los, his = [], [], [], []
        for i, v in enumerate(order[inst]):
            vals = sorted(runs.get((inst, v), []))
            if not vals:
                continue
            xs.append(i)
            meds.append(vals[len(vals) // 2])
            los.append(vals[0])
            his.append(vals[-1])
        ax.errorbar(xs, meds,
                    yerr=[[m - l for m, l in zip(meds, los)],
                          [h - m for m, h in zip(meds, his)]],
                    fmt="o", color=BLUE, capsize=3, lw=2, ms=6,
                    label="median of 3 (range)")
        ax.axhline(frontier[inst], color=BLACK, lw=2, ls="--")
        ax.text(0.1, frontier[inst], " frontier", va="bottom", fontsize=8)
        nat_idx = order[inst].index(str(natural[inst]))
        ax.axvline(nat_idx, color=RED, lw=1.5, ls=":")
        ax.text(nat_idx, ax.get_ylim()[1], " natural sc", fontsize=8, color=RED,
                va="top")
        ax.set_xticks(range(len(order[inst])))
        ax.set_xticklabels([v if v != "inf" else r"$\infty$" for v in order[inst]])
        ax.set_xlabel(r"sc$_{\mathrm{target}}$  [log$_2$ memory]")
        ax.set_ylabel(r"best tc at 90 s  [log$_2$ flops]" if inst == "reg3_250" else "")
        ax.set_title(inst, fontsize=11)
        ax.legend(frameon=False, fontsize=8)
    save(fig, "fig1_sctarget_sweep")


if __name__ == "__main__":
    fig2(); fig3(); fig4(); fig5(); fig6(); fig7(); fig1()
